### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by mikedelafuente** [joshfullmer/todo-database#1]
I believe you can simplify this by just setting "Date date = new Date();" since you are only validating the constructed date - you do not need to create a date from a parsed string as that is unnecessary work.

https://github.com/joshfullmer/todo-database/blob/269fc1862512d2c0273cae20eec9da902de19f22/src/test/java/TodoTest.java#L28-L35

**Comment by joshfullmer** [comment]
Thanks for pointing this out!  Resolved.
